/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Edit: typeof import('./../../components/Modals/users/edit.vue')['default']
    Header: typeof import('./../../components/Header/index.vue')['default']
    HeaderMenu: typeof import('./../../components/Header/headerMenu.vue')['default']
    HomeComponent: typeof import('./../../components/homeComponent.vue')['default']
    InputForm: typeof import('./../../components/Forms/inputForm.vue')['default']
    Modals: typeof import('./../../components/Modals/index.vue')['default']
    Registration: typeof import('./../../components/Modals/registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
