/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./../../components/Header/index.vue')['default']
    HeaderMenu: typeof import('./../../components/Header/headerMenu.vue')['default']
    HeaderNav: typeof import('./../../components/Header/headerNav.vue')['default']
    HomeComponent: typeof import('./../../components/homeComponent.vue')['default']
    Input: typeof import('../../components/Forms/inputForm.vue')['default']
    InputForm: typeof import('./../../components/Forms/inputForm.vue')['default']
    Menu: typeof import('./src/components/Header/menu.vue')['default']
    RegistrationPage: typeof import('../../pages/registrationPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
